version: '3.6'

services:
  hapi-fhir-jpaserver:
    image: hapiproject/hapi:latest
    container_name: hapi-fhir-jpaserver
    restart: on-failure
    ports:
      - 6060:8080
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
  
  measure-authoring-tool:
    image: measure-authoring-tool
    container_name: MeasureAuthoringTool
    build:
      context: MeasureAuthoringTool
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - 8080:8080
    depends_on:
      - mat-mysql

    extra_hosts:
      - "host.docker.internal:172.17.0.1"

  cql-elm-translation:
    image: cql-elm-translation
    container_name: cql-elm-translation
    build:
      context: cql-elm-translation
      dockerfile: Dockerfile
    environment:
      FHIR_SERVICES_URL: ${FHIR_SERVICES_URL}
      CQL_ELM_SWAGGER_URL: ${CQL_ELM_SWAGGER_URL}
      MAT_API_KEY: ${MAT_API_KEY}
      LOG_LEVEL: ${LOG_LEVEL}
    restart: on-failure
    ports:
      - 7070:7070
    depends_on:
      - mat-mysql
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

  mapping-services:
    image: mapping-services
    container_name: mapping-services
    build:
      context: mapping-services
      dockerfile: Dockerfile
    environment:
      GOOGLE_MAT_ATTRIBUTES_URL: ${GOOGLE_MAT_ATTRIBUTES_URL}
      GOOGLE_QDM_QI_CORE_MAPPING_URL: ${GOOGLE_QDM_QI_CORE_MAPPING_URL}
      GOOGLE_DATA_TYPES_URL: ${GOOGLE_DATA_TYPES_URL}
      GOOGLE_REQUIRED_MEASURE_FIELDS_URL: ${GOOGLE_REQUIRED_MEASURE_FIELDS_URL}
      GOOGLE_RESOURCE_DEFINITION_URL: ${GOOGLE_RESOURCE_DEFINITION_URL}
      MAPPING_SWAGGER_URL: ${MAPPING_SWAGGER_URL}
      MAT_API_KEY: ${MAT_API_KEY}
      LOG_LEVEL: ${LOG_LEVEL}
    restart: on-failure
    ports:
      - 9090:9090
    depends_on:
      - mat-mysql
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

  mat-fhir-services:
    image: mat-fhir-services
    container_name: mat-fhir-services
    build:
      context: mat-fhir-services
      dockerfile: Dockerfile
      args:
        ENV: ${ENV}
    environment:
      JAVA_TOOL_OPTIONS: ${JAVA_TOOL_OPTIONS}
      VSAC_TICKET_URL_BASE: ${VSAC_TICKET_URL_BASE}
      VSAC_URL_BASE: ${VSAC_URL_BASE}
      MAT_DB_URL: ${MAT_DB_URL}
      MAT_DB_PASS: ${MAT_DB_PASS}
      MAT_DB_USER: ${MAT_DB_USER}
      HAPI_FHIR_URL: ${HAPI_FHIR_URL}
      CQL_CONVERSION_URL: ${CQL_CONVERSION_URL}
      FHIR_SERVICES_URL: ${FHIR_SERVICES_URL}
      CODESYSTEM_SHEET_URL: ${CODESYSTEM_SHEET_URL}
      HAPI_FHIR_URL_PUBLIC: ${HAPI_FHIR_URL_PUBLIC}
      MAT_FHIR_SWAGGER_URL: ${MAT_FHIR_SWAGGER_URL}
      MAPPING_SERVICES_URL: ${MAPPING_SERVICES_URL}
      MAT_API_KEY: ${MAT_API_KEY}
      LOG_LEVEL: ${LOG_LEVEL}
    restart: on-failure
    ports:
      - 9080:9080
    depends_on:
      - mat-mysql
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
  
  mat-mysql:
    image: mat-mysql
    container_name: mat-mysql
    build:
      context: mysql
      dockerfile: Dockerfile
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: adminadmin
      MYSQL_USER: admin
      MYSQL_PASSWORD: adminadmin
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: MAT_APP_BLANK
    ports:
      - 3307:3306
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
